import Head from 'next/head'
import DisplayProducts from '../components/DisplayProducts'
import Slider from '../components/Slider'
import Support from '../components/Support'

export default function Home() {
    return (
        <div>
            <Head>
                <title>Qapple - The easy shopping</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Slider />
            <DisplayProducts title="Featured Products" />
            <Support />
        </div>
    )
}
